# Generated by Django 3.2 on 2023-05-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name for category')),
                ('slug', models.SlugField(max_length=20, verbose_name='URL for group')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name for genre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL of group')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name for title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description for title')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.category')),
                ('genre', models.ManyToManyField(related_name='titles', to='api.Genre')),
            ],
        ),
    ]
